#!/usr/bin/env bash
# AUTHOR: M. H. IMAM (FxP1998)
# GITHUB: https://github.com/FxP1998

# --- Colors ---
BLUE="\033[1;34m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
RED="\033[1;31m"
RESET="\033[0m"
BOLD="\033[1m"

echo -e "${BLUE}▶ MAKO & MATUGEN INTEGRATION SETUP${RESET}"

# -----------------------------------------------------
# 1. Install Packages
# -----------------------------------------------------
PACKAGES=(mako wayland libxkbcommon pango cairo libnotify)
MISSING_PACKAGES=()

echo -e "${BLUE}:: Checking installed packages...${RESET}"

for pkg in "${PACKAGES[@]}"; do
  if pacman -Qi "$pkg" &>/dev/null; then
    echo -e "${GREEN} ✔ $pkg is installed${RESET}"
  else
    echo -e "${YELLOW} ✘ $pkg is missing${RESET}"
    MISSING_PACKAGES+=("$pkg")
  fi
done

if [ ${#MISSING_PACKAGES[@]} -gt 0 ]; then
  echo -e "\n${BLUE}:: Installing missing packages...${RESET}"
  sudo pacman -S --needed --noconfirm "${MISSING_PACKAGES[@]}"
fi

# -----------------------------------------------------
# 2. Create Matugen Template
# -----------------------------------------------------
# User requested path: ~/.config/matugen/templates/mako
TEMPLATE_DIR="$HOME/.config/matugen/templates"
TEMPLATE_FILE="$TEMPLATE_DIR/mako"

echo -e "\n${BLUE}:: Creating Mako Template in Matugen folder...${RESET}"
mkdir -p "$TEMPLATE_DIR"

cat > "$TEMPLATE_FILE" << 'EOF'
# -----------------------------------------------------------------------------
# MAKO CONFIGURATION (Matugen Template)
# -----------------------------------------------------------------------------

# --- Colors (Generated by Matugen) ---
background-color={{colors.surface.default.hex}}D9
text-color={{colors.on_surface.default.hex}}
border-color={{colors.primary.default.hex}}
progress-color=source {{colors.primary.default.hex}}

# --- Typography ---
font=MapleMono NF Mono 12

# --- Window Geometry ---
width=350
height=150
margin=20
padding=15
border-size=2
border-radius=15

# --- Positioning ---
anchor=top-right

# --- Behavior ---
default-timeout=5000
ignore-timeout=1
icons=1
max-icon-size=48
icon-location=left
markup=1
actions=1
history=1

# --- Grouping ---
group-by=app-name

# --- Urgency Styles ---
[urgency=low]
border-color={{colors.secondary.default.hex}}
text-color={{colors.on_surface_variant.default.hex}}

[urgency=normal]
border-color={{colors.primary.default.hex}}

[urgency=critical]
border-color={{colors.error.default.hex}}
text-color={{colors.error.default.hex}}
default-timeout=0
EOF

echo -e "${GREEN}✔ Template saved to: $TEMPLATE_FILE${RESET}"

# -----------------------------------------------------
# 3. Configure Matugen (config.toml)
# -----------------------------------------------------
MATUGEN_CONFIG="$HOME/.config/matugen/config.toml"
mkdir -p "$(dirname "$MATUGEN_CONFIG")"

# We check if the [templates.mako] block already exists to avoid duplication
if grep -q "\[templates.mako\]" "$MATUGEN_CONFIG"; then
    echo -e "${YELLOW}⚠ [templates.mako] already exists in config.toml. Skipping append.${RESET}"
else
    echo -e "${BLUE}:: Adding Mako entry to Matugen config...${RESET}"
    
    # NOTE: We output to ~/.config/mako/config because Mako 
    # does NOT support include files (like mako-colors).
    cat >> "$MATUGEN_CONFIG" << EOF

[templates.mako]
input_path = '$TEMPLATE_FILE'
output_path = '~/.config/mako/config'
post_hook = 'makoctl reload'
EOF
    echo -e "${GREEN}✔ config.toml updated!${RESET}"
fi

# -----------------------------------------------------
# 4. Final Instructions
# -----------------------------------------------------
echo -e "\n${BOLD}-----------------------------------------------------${RESET}"
echo -e "${GREEN}✔ SETUP COMPLETE!${RESET}"
echo -e "${BOLD}-----------------------------------------------------${RESET}"
echo -e "Your system is now configured."
echo -e "To apply the theme now, simply run:"
echo -e "   ${YELLOW}matugen image /path/to/your/wallpaper.png${RESET}"
echo -e "${BOLD}-----------------------------------------------------${RESET}"
