# AUTHOR: M. H. IMAM (FxP1998)
# GITHUB: https://github.com/FxP1998

# --------------------------------
# CHARGER: MAX PERFORMANCE
# --------------------------------
[charger]
# Max speed when plugged in
governor = performance

# Aggressiveness (0-255 or string). 'performance' = 0
energy_performance_preference = performance

# Allow CPU to boost above base frequency
turbo = auto

# --------------------------------
# BATTERY: MAX SAVING
# --------------------------------
[battery]
# Slow down when unplugged
governor = powersave

# Aggressiveness. 'power' tells CPU to prioritize efficiency
energy_performance_preference = power

# Intel users: 'power' bias helps deeper sleep states
energy_perf_bias = power

# Platform Profile (if supported by laptop firmware)
platform_profile = low-power

# CRITICAL: Disable Turbo on battery. 
# This prevents random CPU spikes that kill battery life.
turbo = never
