#!/usr/bin/env bash
# AUTHOR: M. H. IMAM (FxP1998)
# DESCRIPTION: Unified Media, Hardware & Power Tuning Script (Official)

# --- Colors & Compatibility Engine ---
C_BLUE='\033[1;34m'; C_GREEN='\033[1;32m'; C_YELLOW='\033[1;33m'; C_RED='\033[1;31m'; C_RESET='\033[0m'; C_BOLD='\033[1m'

if [[ "$TERM" == "linux" ]]; then
    # TTY SAFE MODE (Standard ASCII)
    I_CHECK="[OK]"; I_GEAR="[*]"; I_INFO="->"; I_POWER="[P]"; I_MEDIA="[M]"; I_GPU="[G]"; LINE="----------------------------------------------------"
else
    # GUI CANDY MODE (Nerd Fonts)
    I_CHECK="󰄬"; I_GEAR="󰒓"; I_INFO="󰁔"; I_POWER="󰐥"; I_MEDIA="󰝚"; I_GPU="󰢮"; LINE="━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
fi

# --- Helper Functions ---
print_header() {
    clear
    echo -e "${C_BLUE}${C_BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${C_RESET}"
    echo -e "  ${I_GEAR}  ${C_BOLD}Hardware & Media Optimization${C_RESET}"
    echo -e "${C_BLUE}${C_BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${C_RESET}\n"
}

print_step() { echo -e "  ${C_BLUE}${C_BOLD}[${C_RESET}${I_GEAR}${C_BLUE}${C_BOLD}]${C_RESET} $1"; }
print_success() { echo -e "  ${C_GREEN}${C_BOLD}[${C_RESET}${I_CHECK}${C_GREEN}${C_BOLD}]${C_RESET} $1"; }
print_error() { echo -e "  ${C_RED}${C_BOLD}[󰅖]${C_RESET} $1"; }

# --- 1. Audio Conflict Resolution ---
tune_audio() {
    print_step "Checking for Audio Server Conflicts..."
    if pacman -Qs jack2 > /dev/null; then
        echo -e "      ${I_INFO} Found legacy jack2. Removing to favor Pipewire-Jack..."
        sudo pacman -Rdd --noconfirm jack2 &>/dev/null
        print_success "Jack conflict resolved."
    else
        echo -e "      ${I_INFO} Audio environment clean."
    fi
}

# --- 2. MPV Hardware Acceleration Tuning ---
tune_mpv() {
    print_step "Tuning MPV for High-Stability Hardware Decoding..."
    local CONF_DIR="$HOME/.config/mpv"
    local CONF_FILE="$CONF_DIR/mpv.conf"
    
    mkdir -p "$CONF_DIR"

    # Detect GPU
    local HAS_AMD=$(lspci | grep -i "AMD/ATI")
    local HAS_INTEL=$(lspci | grep -i "Intel")
    local HAS_NVIDIA=$(lspci | grep -i "NVIDIA")
    local HWDEC="auto-safe"

    if [[ -n "$HAS_NVIDIA" ]]; then
        echo -e "      ${I_GPU} NVIDIA detected. Using NVDEC."
        HWDEC="nvdec"
    elif [[ -n "$HAS_AMD" || -n "$HAS_INTEL" ]]; then
        echo -e "      ${I_GPU} Integrated/AMD detected. Using VA-API."
        HWDEC="vaapi"
    fi

    cat <<EOF > "$CONF_FILE"
# 2025 High-Stability Universal Config
# Generated by FxP Tuning Script
vo=gpu
gpu-api=opengl
hwdec=$HWDEC
save-position-on-quit=yes
video-sync=display-resample
interpolation=yes
tscale=oversample
EOF
    print_success "MPV optimized (OpenGL mode for VK stability)."
}

# --- 3. Power Optimization (auto-cpufreq) ---
tune_power() {
    print_step "Configuring Power Management (User Level)..."
    local USER_CONFIG_DIR="$HOME/.config/auto-cpufreq"
    local USER_CONFIG="$USER_CONFIG_DIR/auto-cpufreq.conf"
    local SYSTEM_CONFIG="/etc/auto-cpufreq.conf"

    # Create user-level config directory
    mkdir -p "$USER_CONFIG_DIR"

    # Write the Official FxP1998 Configuration to user space
    cat <<EOF > "$USER_CONFIG"
# AUTHOR: M. H. IMAM (FxP1998)
# GITHUB: https://github.com/FxP1998

# --------------------------------
# CHARGER: MAX PERFORMANCE
# --------------------------------
[charger]
governor = performance
energy_performance_preference = performance
turbo = auto

# --------------------------------
# BATTERY: MAX SAVING
# --------------------------------
[battery]
governor = powersave
energy_performance_preference = power
energy_perf_bias = power
platform_profile = low-power
turbo = never
EOF

    echo -e "      ${I_POWER} Deploying config to system and enabling service..."
    # Copy from user space to system space
    sudo cp "$USER_CONFIG" "$SYSTEM_CONFIG"
    
    sudo systemctl enable --now auto-cpufreq.service &>/dev/null
    sudo systemctl restart auto-cpufreq.service &>/dev/null
    print_success "Power profiles deployed to $USER_CONFIG and $SYSTEM_CONFIG"
}

# --- Execution ---
print_header

tune_audio
echo ""
tune_mpv
echo ""
tune_power

echo -e "\n${C_GREEN}${C_BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${C_RESET}"
print_success "Hardware & Media Tuning Complete!"
echo -e "  ${I_INFO} MPV, Audio, and CPU Power are now optimized."
echo -e "${C_GREEN}${C_BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${C_RESET}"
