rootcolor={{colors.background.default.hex_stripped}}ff

bordercolor={{colors.outline_variant.default.hex_stripped}}ff

focuscolor={{colors.primary_container.default.hex_stripped}}ff

maxmizescreencolor={{colors.secondary.default.hex_stripped}}ff

urgentcolor={{colors.error.default.hex_stripped}}ff

scratchpadcolor={{colors.tertiary.default.hex_stripped}}ff

globalcolor={{colors.secondary_container.default.hex_stripped}}ff

overlaycolor={{colors.tertiary_container.default.hex_stripped}}ff
