# : Manager [[[

[mgr]
cwd = { fg = "#e2e2e2" }

# Tab
tab_active = { fg = "#1b2678", bg = "#bcc2ff", bold = true }
tab_inactive = { fg = "#dfe0ff", bg = "#000b62" }
tab_width = 1

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#ff71ca", bg = "#ff71ca" }
marker_cut      = { fg = "#ffd7f0", bg = "#ffd7f0" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e6bad6", bg = "#e6bad6" }

# Count
count_copied   = { fg = "#2d1127", bg = "#ffd7f0" }
count_cut      = { fg = "#2d1127", bg = "#ffd7f0" }
count_selected = { fg = "#1b2678", bg = "#e6bad6" }

# Border
border_symbol = "│"
border_style  = { fg = "#bcc2ff" }

# : ]]]


# : Indicator [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#1b2678", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#bcc2ff", fg = "#1b2678", bold = true }
normal_alt  = { bg = "#474747", fg = "#c6c6c6" }

# Select mode
select_main = { bg = "#c4c5dd", fg = "#2d2f42", bold = true }
select_alt  = { bg = "#474747", fg = "#c6c6c6" }

# Unset mode
unset_main = { bg = "#e6bad6", fg = "#45263d", bold = true }
unset_alt  = { bg = "#474747", fg = "#c6c6c6" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#bcc2ff", bg = "#393939" }
progress_error  = { fg = "#ffb4ab", bg = "#393939" }

# Permissions
permissions_type = { fg = "#6366a5" }
permissions_write = { fg = "#bd4a93" }
permissions_exec = { fg = "#ff2b12" }
permissions_read = { fg = "#ff3eb7" }
permissions_sep = { fg = "#464cff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#bcc2ff" }
active = { fg = "#e6bad6", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#bcc2ff" }
value  = { fg = "#e2e2e2" }

# : ]]]

# : Tabs [[[

[tabs]
active    = { fg = "#bcc2ff", bold = true, bg = "#131313" }
inactive  = { fg = "#c4c5dd", bg = "#131313" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#bcc2ff", bg = "#1b2678" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#bcc2ff" }
title   = {}
hovered = { fg = "#ffd7f0", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#393939" }
cand = { fg = "#bcc2ff" }
rest = { fg = "#1b2678" }
desc = { fg = "#e2e2e2" }
separator = " ▶ "
separator_style = { fg = "#e2e2e2" }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e2e2e2" }
run    = { fg = "#e2e2e2" }
footer = { fg = "#2d2f42", bg = "#c4c5dd" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e6bad6" }
title_warn = { fg = "#bcc2ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e2e2e2" },
    { url = "*/", fg = "#bcc2ff" },
]

# : ]]]
