# -----------------------------------------------------------------------------
#  󰣇  HYPRLAND CONFIGURATION
#  󰀻  File: 01-autostart.conf
#  󰁔  Description: Background services and startup applications.
#
#  󰄬  Created By: M. H. IMAM (FxP1998)
#  󰊤  GitHub: https://github.com/FxP1998/
# -----------------------------------------------------------------------------

# == Core System Services ==
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1       # Polkit Agent
exec-once = waybar &                                                        # Status Bar
exec-once = swww-daemon &                                                   # Wallpaper Daemon
exec-once = dunst &                                                         # Notifications
exec-once = swayosd-server &                                                # OSD Server (Volume/Brightness)
exec-once = udiskie -ant                                                    # Auto-mounter
exec-once = nm-applet &                                                     # Network Manager

# == Hyprland Eco System ==
exec-once = hypridle							    # Hyprland idel manager (or management)

# == Clipboard Manager ==
exec-once = wl-paste --type text --watch cliphist store                     # Text Clipboard
exec-once = wl-paste --type image --watch cliphist store                    # Image Clipboard

# == User Applications ==
exec-once = blueman-applet                                                  # Bluetooth

# == Custom Scripts ==
exec-once = $HOME/.config/hypr/config/copy.sh
exec-once = $HOME/.config/hypr/scripts/battery-monitor/battery-monitor.sh &					# Battery Monitor
exec-once = $HOME/.config/hypr/scripts/swww/swww-wallpaper-changer/set-wall-on-boot.sh &				# Set Random Wallpaper On Boot Only	
