# -----------------------------------------------------------------------------
#  󰣇  HYPRLAND CONFIGURATION
#  󰀻  File: 04-hypr-colors.conf
#  󰁔  Description: Global color variables and Matugen source.
#
#  󰄬  Created By: M. H. IMAM (FxP1998)
#  󰊤  GitHub: https://github.com/FxP1998/
# -----------------------------------------------------------------------------

# --- CORE COLORS ---
$background = rgb(131313)
$on_background = rgb(e2e2e2)

$surface = rgb(131313)
$on_surface = rgb(e2e2e2)

# --- ACCENT COLORS ---
$primary = rgb(d2bbff)
$on_primary = rgb(3b1d71)

$secondary = rgb(cdc2db)
$on_secondary = rgb(342d40)

$tertiary = rgb(f0b7c5)
$on_tertiary = rgb(4a2530)

$error = rgb(ffb4ab)
$on_error = rgb(690005)

# --- UI ELEMENTS ---
$outline = rgb(919191)
$outline_variant = rgb(474747)
$shadow = rgb(000000)

# --- CONTAINERS (Useful for "Card" backgrounds) ---
$surface_container = rgb(1f1f1f)
$surface_container_high = rgb(2a2a2a)
$surface_container_highest = rgb(353535)

# --- BORDER VARIABLES (Ready to use) ---
# Active: Primary -> Secondary Gradient
$active_border_col = $primary $secondary 45deg

# Inactive: Outline Variant (Subtle Grey)
$inactive_border_col = $outline_variant

# Error/Critical Window Border
$urgent_border_col = $error
