# -----------------------------------------------------------------------------
#  HYPRLAND CONFIGURATION (05-look.conf)
#  Created By: M. H. IMAM
#  GitHub: https://github.com/FxP1998/
# -----------------------------------------------------------------------------

# == Source Colors ==
source = $HOME/.config/hypr/modules/04-hypr-colors.conf

# == General Settings ==
general {
    gaps_in = 3
    gaps_out = 6
    border_size = 2

    # Updated to use Matugen variables
    col.active_border = $active_border_col
    col.inactive_border = $inactive_border_col

    resize_on_border = true
    allow_tearing = false
    layout = dwindle

    snap {
        enabled = true
    }
}

# == Decoration Settings ==
decoration {
    rounding = 6
    rounding_power = 3

    active_opacity = 0.95
    inactive_opacity = 0.85

    dim_inactive = true
    dim_strength = 0.1

    shadow {
        enabled = true
        range = 6
        render_power = 2

        color = $primary
        color_inactive = $shadow

        sharp = false
        ignore_window = true
    }

    blur {
        enabled = true
        size = 4
        passes = 4
        contrast = 1
        vibrancy = 0.500
        new_optimizations = true
        xray = false
        popups = false
    }
}
