# -----------------------------------------------------------------------------
#  󰣇  HYPRLAND CONFIGURATION
#  󰀻  File: 07-env.conf
#  󰁔  Description: Environment variables and driver optimization.
#
#  󰄬  Created By: M. H. IMAM (FxP1998)
#  󰊤  GitHub: https://github.com/FxP1998/
# -----------------------------------------------------------------------------

# == HARDWARE VIDEO ACCELERATION ==
env = LIBVA_DRIVER_NAME,radeonsi
env = VDPAU_DRIVER,radeonsi
env = MOZ_DISABLE_RDD_SANDBOX,1

# == WAYLAND BACKENDS ==
env = GDK_BACKEND,wayland,x11
env = MOZ_ENABLE_WAYLAND,1
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
env = QT_STYLE_OVERRIDE,gtk2
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = GTK_USE_PORTAL,1

# == QT CONFIGURATION ==
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_STYLE_OVERRIDE,Kvantum

# == HYPRLAND SPECIFIC ==
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
