# -----------------------------------------------------------------------------
#  󰣇  HYPRLAND CONFIGURATION
#  󰀻  File: 08-var.conf
#  󰁔  Description: XWayland and internal Hyprland variables.
#
#  󰄬  Created By: M. H. IMAM (FxP1998)
#  󰊤  GitHub: https://github.com/FxP1998/
# -----------------------------------------------------------------------------

xwayland {
    enabled = true
    use_nearest_neighbor = true
    force_zero_scaling = false
}

render {
    direct_scanout = 2 
    new_render_scheduling = true 
}

cursor {
    hide_on_key_press = true
}

ecosystem {
    no_update_news = false
    no_donation_nag = true
}
