# -----------------------------------------------------------------------------
#  󰣇  HYPRLAND CONFIGURATION
#  󰀻  File: 11-rules.conf
#  󰁔  Description: Window-specific behaviors and placement rules.
#
#  󰄬  Created By: M. H. IMAM (FxP1998)
#  󰊤  GitHub: https://github.com/FxP1998/
# -----------------------------------------------------------------------------

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}


# nwg-look
windowrule {
    name = nwg-look
    match:class = nwg-look
    float = on
    size = 800 500
}

# Dolphin
windowrule {
    name = dolphin
    match:class = org.kde.dolphin
    float = on
    size = 800 500
}

# Thunar & File Dialogs
windowrule {
    name = file dialogs
    match:class = xdg-desktop-portal-gtk
    match:title = .*
    float = on
    size = 800 500
    move = 580 290
}

windowrule {
    name = nautilus
    match:class = org.gnome.Nautilus
    float = on
    size = 800 500
    move = 1100 290
}

windowrule {
    name = thunar
    match:class = thunar
    match:title = File Operation Progress|Confirm to replace files
    float = on
    size = 300 300
}

# Bluetooth & Network
windowrule {
    name = bluetooth
    match:class = blueman-manager
    match:title = Bluetooth Devices
    float = on
    size = 600 400
}

windowrule {
    name = network-manager-applet
    match:class = nm-connection-editor
    match:title = Network Connections
    float = on
    size = 700 400
}

# Calculator
windowrule {
    name = gnome-calculator
    match:title = Calculator
    match:class = org.gnome.Calculator
    float = on
    move = 1455 457
}


# General floating terminals (System Update, nmtui, etc)
windowrule {
    name = Temporary Floating
    match:title = System Update|nmtui_fxp-hyprland|fxp-tmp
    float = on
    size = 700 650
    move = 1200 215
}

# Music player
windowrule {
    name = kew
    match:class = kitty
    match:title = kew
    float = on
    size = 1200 700
    center = on
    maximize = on
    workspace = 5
}


# Volume & Multimedia
windowrule = float on, size 800 500, move 560 290, match:class ^(org.pulseaudio.pavucontrol)$, match:title ^(Volume Control)$
windowrule = float on, match:class ^(vlc)$

# File chooser dialogs
windowrule = float on, match:title ^(Open File|Save File|File Upload|Choose Files)$

# Browsers (Firefox/Chromium)
windowrule = float on, match:class ^(firefox|chromium)$, match:title ^(Library|Picture-in-Picture|Extension:.*)$

# Archivers & File Managers
windowrule = float on, match:class ^(org.gnome.FileRoller|org.gnome.Nautilus)$
