# -----------------------------------------------------------------------------
#  HYPRLAND CONFIGURATION (13-security.conf)
#  Created By: M. H. IMAM
#  GitHub: https://github.com/FxP1998/
# -----------------------------------------------------------------------------

ecosystem {
  enforce_permissions = 1
}

# == Permissions ==
# Screen Recording & Sharing (screencopy)
permission = /usr/(bin|local/bin)/grim, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/(bin|local/bin)/wf-recorder, screencopy, allow
permission = /usr/(bin|local/bin)/obs, screencopy, allow
permission = /usr/(bin|local/bin)/hyprlock, screencopy, allow

# Plugin Management
permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
