# -----------------------------------------------------------------------------
#  󰣇  HYPRLAND CONFIGURATION
#  󰀻  File: 14-layerrules.conf
#  󰁔  Description: Layer-specific rules for Rofi, Mako and others.
#
#  󰄬  Created By: M. H. IMAM (FxP1998)
#  󰊤  GitHub: https://github.com/FxP1998/
# -----------------------------------------------------------------------------

# Enable blur and ignore transparency so the glass effect works
layerrule {
    name = rofi
    blur = on
    ignore_alpha = 0
    match:namespace = rofi
}

# Enable blur for notifications
layerrule {
    name = notifications
    blur = on
    ignore_alpha = 0
    match:namespace = notifications
}
# Fallback for some versions of Mako
layerrule {
    name = mako
    blur = on
    ignore_alpha = 0
    match:namespace = mako
}

# Disable animations so it opens instantly (snappier feel)
layerrule {
    name = wlogout
    no_anim = on
    match:namespace = wlogout
}

# Disable entry animation to prevent the "Black Flash" issue
layerrule {
    name = hyprlock
    no_anim = on
    match:namespace = hyprlock
}
