" Auto-generated by Matugen for Vim
set background=dark
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "matugen"

" --- UI & BACKGROUNDS ---
hi Normal       guifg=#e2e2e2 guibg=NONE ctermbg=NONE
hi LineNr       guifg=#474747 guibg=NONE
hi SignColumn   guibg=NONE
hi CursorLineNr guifg=#d2bbff     guibg=NONE gui=bold
hi CursorLine   guibg=#1f1f1f
hi Visual       guifg=#eaddff guibg=#523689
hi VertSplit    guifg=#474747 guibg=NONE gui=NONE
hi EndOfBuffer  guifg=#131313      guibg=NONE

" --- STATUS LINE (Transparent) ---
hi clear StatusLine
hi clear StatusLineNC
hi StatusLine   guifg=#919191 guibg=NONE ctermbg=NONE gui=NONE
hi StatusLineNC guifg=#474747 guibg=NONE ctermbg=NONE gui=NONE

" --- BOX TYPE POPUP MENU ---
" Pmenu: The Box Background
hi Pmenu        guifg=#e2e2e2 guibg=#1f1f1f
" PmenuSel: Selected Item
hi PmenuSel     guifg=#3b1d71 guibg=#d2bbff gui=bold

" --- GLOWING TEXT PALETTE ---
hi User1 guifg=#d2bbff guibg=NONE ctermbg=NONE gui=bold
hi User2 guifg=#cdc2db guibg=NONE ctermbg=NONE gui=bold
hi User3 guifg=#ffb4ab guibg=NONE ctermbg=NONE gui=bold
hi User4 guifg=#f0b7c5 guibg=NONE ctermbg=NONE gui=bold

" --- SYNTAX HIGHLIGHTING ---
hi Comment      guifg=#919191 gui=italic
hi Constant     guifg=#f0b7c5
hi String       guifg=#d2bbff
hi Identifier   guifg=#cdc2db
hi Function     guifg=#d2bbff
hi Statement    guifg=#f0b7c5 gui=bold
hi Type         guifg=#f0b7c5
hi Special      guifg=#d2bbff

" ==========================================================
"  RICE ADDITIONS (NERDTree, Startify, FZF)
" ==========================================================

" --- NERDTree Sidebar ---
hi NERDTreeDir      guifg=#d2bbff gui=bold
hi NERDTreeOpenable guifg=#f0b7c5
hi NERDTreeClosable guifg=#f0b7c5
hi NERDTreeFile     guifg=#e2e2e2
hi NERDTreeExecFile guifg=#cdc2db gui=bold
hi NERDTreeUp       guifg=#919191
hi NERDTreeCWD      guifg=#f0b7c5 gui=bold

" --- Startify Dashboard (FxP1998 Header) ---
hi StartifyHeader   guifg=#d2bbff gui=bold
hi StartifyFile     guifg=#e2e2e2
hi StartifyPath     guifg=#919191
hi StartifySlash    guifg=#474747
hi StartifyBracket  guifg=#474747
hi StartifyNumber   guifg=#cdc2db
hi StartifySection  guifg=#f0b7c5 gui=bold

" --- FZF & Search ---
hi Search       guifg=#3b1d71 guibg=#d2bbff
hi IncSearch    guifg=#342d40 guibg=#cdc2db
