cursor            #d2bbff
cursor_text_color #3b1d71

foreground            #e2e2e2
background            #131313
selection_foreground  #342d40
selection_background  #cdc2db
url_color             #cdc2db

#: black 000000 767676
color0  #131313
color8  #353535
#: red cc0403 f2201f
color1  #3b1d1b
color9  #a4504b
#: green 19cb00 23fd00
color2  #cdc2db
color10 #e9def8
#: yellow cecb00 fffd00
color3  #f0b7c5
color11 #ffd9e1
#: blue 0d73cc 1a8fff
color4  #523689
color12 #d2bbff
#: magenta cb1ed1 fd28ff
color5  #4b4358
color13 #cdc2db
#: cyan 0dcdcd 14ffff
color6  #643b46
color14 #f0b7c5
#: white dddddd ffffff
color7  #c6c6c6
color15 #e2e2e2

mark1_foreground #25005a
mark1_background #eaddff
mark2_foreground #1e182b
mark2_background #e9def8
mark3_foreground #31101b
mark3_background #ffd9e1

active_tab_foreground #3b1d71
active_tab_background #d2bbff
inactive_tab_foreground #eaddff
inactive_tab_background #523689

active_border_color #d2bbff
inactive_border_color #3b1d71
# bell_border_color #ff5a00
