cursor            #80d997
cursor_text_color #00391a

foreground            #e2e2e2
background            #131313
selection_foreground  #223526
selection_background  #b7ccb7
url_color             #b7ccb7

#: black 000000 767676
color0  #131313
color8  #353535
#: red cc0403 f2201f
color1  #345d41
color9  #77b389
#: green 19cb00 23fd00
color2  #b7ccb7
color10 #d2e8d3
#: yellow cecb00 fffd00
color3  #a2ced9
color11 #bdeaf5
#: blue 0d73cc 1a8fff
color4  #005228
color12 #80d997
#: magenta cb1ed1 fd28ff
color5  #394b3c
color13 #b7ccb7
#: cyan 0dcdcd 14ffff
color6  #204d56
color14 #a2ced9
#: white dddddd ffffff
color7  #c6c6c6
color15 #e2e2e2

mark1_foreground #00210c
mark1_background #9cf6b2
mark2_foreground #0e1f12
mark2_background #d2e8d3
mark3_foreground #001f25
mark3_background #bdeaf5

active_tab_foreground #00391a
active_tab_background #80d997
inactive_tab_foreground #9cf6b2
inactive_tab_background #005228

active_border_color #80d997
inactive_border_color #00391a
# bell_border_color #ff5a00
