# -----------------------------------------------------------------------------
#  KITTY CONFIGURATION
#  Created By: M. H. IMAM
#  GitHub: https://github.com/FxP1998/
# -----------------------------------------------------------------------------

# --- THEME & COLORS ---
# Import Matugen generated colors
include ~/.config/kitty/colors.conf

# --- FONTS ---
font_family      MapleMono NF
bold_font        MapleMono NF Bold
italic_font      MapleMono NF Italic
bold_italic_font MapleMono NF Bold Italic
font_size        12.5

# Ligatures & Rendering
disable_ligatures never
font_features     +liga

# --- WINDOW LAYOUT ---
window_padding_width 25
confirm_os_window_close 0
wayland_titlebar_color background

# --- CURSOR ---
# Red "Beam" style with smooth trail
cursor_shape          beam
cursor_blink_interval 1
cursor                #FF0000
cursor_trail          1000
cursor_trail_color    #FF0000
cursor_trail_decay    0.1 0.4

# --- BEHAVIOR & SYSTEM ---
scrollback_lines      3000
enable_audio_bell     yes
bell_path             ~/.config/kitty/assets/ding.ogg

# --- ADDING REMOTE ACCESS TO KITTY ---
allow_remote_control yes

# --- Performance & Wayland ---
linux_display_server  wayland
touch_scroll_multiplier 5.0
