[config]
# ...

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

#[templates.pywalfox]
#input_path = '~/.config/matugen/templates/pywalfox-colors.json'
#output_path = '~/.cache/wal/colors.json'
#post_hook = 'pywalfox update'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.zed]
input_path = '~/.config/matugen/templates/zed-colors.json'
output_path = '~/.config/zed/themes/matugen.json'

[templates.dunst]
input_path = '~/.config/matugen/templates/dunstrc-colors'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'killall dunst; dunst &'

[templates.zathura]
input_path = '~/.config/matugen/templates/zathurarc'
output_path = '~/.config/zathura/zathurarc'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.wlogout]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.swayosd]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swayosd/colors.css'
post_hook = '~/.config/hypr/scripts/swayosd/restart-swayosd.sh'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/modules/04-hypr-colors.conf'
post_hook = 'hyprctl reload'

[templates.neovim]
input_path = "~/.config/matugen/templates/neovim/lua/template.lua"
output_path = "~/.config/nvim/lua/matugen_theme.lua"
post_hook = "pkill -SIGUSR1 nvim || true"

[templates.vim]
input_path = "~/.config/matugen/templates/vim/colors.vim"
output_path = "~/.vim/colors/matugen.vim"

[templates.nano]
input_path = "~/.config/matugen/templates/nano/colors.nanorc"
output_path = "~/.config/nano/matugen.nanorc"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = '~/.config/gtk-4.0/colors.css'

