" Auto-generated by Matugen for Vim
set background=dark
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "matugen"

" --- UI & BACKGROUNDS ---
hi Normal       guifg={{colors.on_surface.default.hex}} guibg=NONE ctermbg=NONE
hi LineNr       guifg={{colors.outline_variant.default.hex}} guibg=NONE
hi SignColumn   guibg=NONE
hi CursorLineNr guifg={{colors.primary.default.hex}}     guibg=NONE gui=bold
hi CursorLine   guibg={{colors.surface_container.default.hex}}
hi Visual       guifg={{colors.on_primary_container.default.hex}} guibg={{colors.primary_container.default.hex}}
hi VertSplit    guifg={{colors.outline_variant.default.hex}} guibg=NONE gui=NONE
hi EndOfBuffer  guifg={{colors.background.default.hex}}      guibg=NONE

" --- STATUS LINE (Transparent) ---
hi clear StatusLine
hi clear StatusLineNC
hi StatusLine   guifg={{colors.outline.default.hex}} guibg=NONE ctermbg=NONE gui=NONE
hi StatusLineNC guifg={{colors.outline_variant.default.hex}} guibg=NONE ctermbg=NONE gui=NONE

" --- BOX TYPE POPUP MENU ---
" Pmenu: The Box Background
hi Pmenu        guifg={{colors.on_surface.default.hex}} guibg={{colors.surface_container.default.hex}}
" PmenuSel: Selected Item
hi PmenuSel     guifg={{colors.on_primary.default.hex}} guibg={{colors.primary.default.hex}} gui=bold

" --- GLOWING TEXT PALETTE ---
hi User1 guifg={{colors.primary.default.hex}} guibg=NONE ctermbg=NONE gui=bold
hi User2 guifg={{colors.secondary.default.hex}} guibg=NONE ctermbg=NONE gui=bold
hi User3 guifg={{colors.error.default.hex}} guibg=NONE ctermbg=NONE gui=bold
hi User4 guifg={{colors.tertiary.default.hex}} guibg=NONE ctermbg=NONE gui=bold

" --- SYNTAX HIGHLIGHTING ---
hi Comment      guifg={{colors.outline.default.hex}} gui=italic
hi Constant     guifg={{colors.tertiary.default.hex}}
hi String       guifg={{colors.primary.default.hex}}
hi Identifier   guifg={{colors.secondary.default.hex}}
hi Function     guifg={{colors.primary.default.hex}}
hi Statement    guifg={{colors.tertiary.default.hex}} gui=bold
hi Type         guifg={{colors.tertiary.default.hex}}
hi Special      guifg={{colors.primary.default.hex}}

" ==========================================================
"  RICE ADDITIONS (NERDTree, Startify, FZF)
" ==========================================================

" --- NERDTree Sidebar ---
hi NERDTreeDir      guifg={{colors.primary.default.hex}} gui=bold
hi NERDTreeOpenable guifg={{colors.tertiary.default.hex}}
hi NERDTreeClosable guifg={{colors.tertiary.default.hex}}
hi NERDTreeFile     guifg={{colors.on_surface.default.hex}}
hi NERDTreeExecFile guifg={{colors.secondary.default.hex}} gui=bold
hi NERDTreeUp       guifg={{colors.outline.default.hex}}
hi NERDTreeCWD      guifg={{colors.tertiary.default.hex}} gui=bold

" --- Startify Dashboard (FxP1998 Header) ---
hi StartifyHeader   guifg={{colors.primary.default.hex}} gui=bold
hi StartifyFile     guifg={{colors.on_surface.default.hex}}
hi StartifyPath     guifg={{colors.outline.default.hex}}
hi StartifySlash    guifg={{colors.outline_variant.default.hex}}
hi StartifyBracket  guifg={{colors.outline_variant.default.hex}}
hi StartifyNumber   guifg={{colors.secondary.default.hex}}
hi StartifySection  guifg={{colors.tertiary.default.hex}} gui=bold

" --- FZF & Search ---
hi Search       guifg={{colors.on_primary.default.hex}} guibg={{colors.primary.default.hex}}
hi IncSearch    guifg={{colors.on_secondary.default.hex}} guibg={{colors.secondary.default.hex}}
