# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e2e2e2"

# Title color for boxes
theme[title]="#80d997"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#b7ccb7"

# Background color of selected item in processes box
theme[selected_bg]="#80d997"

# Foreground color of selected item in processes box
theme[selected_fg]="#00391a"

# Color of inactive/disabled text
theme[inactive_fg]="#c6c6c6"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#a2ced9"

# Cpu box outline color
theme[cpu_box]="#919191"

# Memory/disks box outline color
theme[mem_box]="#919191"

# Net up/down box outline color
theme[net_box]="#919191"

# Processes box outline color
theme[proc_box]="#919191"

# Box divider line and small boxes line color
theme[div_line]="#474747"

# Temperature graph colors
theme[temp_start]="#b7ccb7"
theme[temp_mid]="#80d997"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#b7ccb7"
theme[cpu_mid]="#80d997"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#b7ccb7"
theme[free_mid]=""
theme[free_end]="#394b3c"

# Mem/Disk cached meter
theme[cached_start]="#a2ced9"
theme[cached_mid]=""
theme[cached_end]="#204d56"

# Mem/Disk available meter
theme[available_start]="#80d997"
theme[available_mid]=""
theme[available_end]="#005228"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#b7ccb7"
theme[download_mid]="#80d997"
theme[download_end]="#a2ced9"

# Upload graph colors
theme[upload_start]="#b7ccb7"
theme[upload_mid]="#80d997"
theme[upload_end]="#a2ced9"