#!/bin/bash
# AUTHOR: M. H. IMAM (FxP1998)
# GITHUB: https://github.com/FxP1998

# --- Colors ---
BLUE="\033[1;34m"
GREEN="\033[1;32m"
RED="\033[1;31m"
YELLOW="\033[1;33m"
RESET="\033[0m"

echo -e "${BLUE}▶ STARTING MPV CONFIG GENERATOR (By FxP)...${RESET}"

# Ensure script is run with sudo
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}[ERROR] Please run this script with sudo.${RESET}"
   exit 1
fi

REAL_USER=$SUDO_USER
USER_HOME=$(getent passwd "$REAL_USER" | cut -d: -f6)
CONF_DIR="$USER_HOME/.config/mpv"
CONF_FILE="$CONF_DIR/mpv.conf"

echo -e "${BLUE}:: Step 1: Installing Hybrid/Dual Graphics Drivers...${RESET}"
# We install both Intel and AMD drivers to ensure universal compatibility
pacman -Sy --needed --noconfirm pciutils mpv mesa libva-mesa-driver vulkan-radeon intel-media-driver libva-intel-driver vulkan-intel &> /dev/null
echo -e "${GREEN}✔ Drivers installed.${RESET}"

# Detect GPU presence
HAS_AMD=$(lspci | grep -i "AMD/ATI")
HAS_INTEL=$(lspci | grep -i "Intel")
HAS_NVIDIA=$(lspci | grep -i "NVIDIA")

mkdir -p "$CONF_DIR"

echo -e "${BLUE}:: Step 2: Generating High-Stability Config...${RESET}"
# We use 'gpu-api=opengl' to prevent Vulkan 'Device Lost' errors
cat <<EOF > "$CONF_FILE"
# 2025 High-Stability Universal Config
# Generated by FxP Script
vo=gpu
gpu-api=opengl
hwdec=auto-safe
save-position-on-quit=yes
# Better handling for high-res videos
video-sync=display-resample
interpolation=yes
tscale=oversample
EOF

# Step 3: Priority Logic
echo -e "${BLUE}:: Step 3: Configuring Hardware Acceleration...${RESET}"
if [[ -n "$HAS_NVIDIA" ]]; then
    echo -e "${YELLOW}➤ NVIDIA detected. Setting up NVDEC...${RESET}"
    pacman -S --needed --noconfirm nvidia-utils libva-vdpau-driver &> /dev/null
    echo "hwdec=nvdec" >> "$CONF_FILE"
elif [[ -n "$HAS_AMD" ]]; then
    echo -e "${YELLOW}➤ AMD Dedicated GPU detected. Setting up VA-API...${RESET}"
    echo "hwdec=vaapi" >> "$CONF_FILE"
elif [[ -n "$HAS_INTEL" ]]; then
    echo -e "${YELLOW}➤ Intel Integrated GPU detected. Setting up VA-API...${RESET}"
    echo "hwdec=vaapi" >> "$CONF_FILE"
fi

# Fix ownership
chown -R "$REAL_USER":"$REAL_USER" "$CONF_DIR"

echo -e "${GREEN}✔ DONE! MPV is configured.${RESET}"
echo -e "${BLUE}▶ Switched to OpenGL to fix 'VK_ERROR_DEVICE_LOST'.${RESET}"
